ENH: build dummy runTimePostProcessing if VTK/ParaView are not available
- this allows more use of the runTimePostProcessing functionObject
  that will fail more gracefully if the proper version could not be
  built.

  The dummy functionObject simply emits a message that it is not available.

diff --git a/src/runTimePostProcessing/Allwmake b/src/runTimePostProcessing/Allwmake
--- a/src/runTimePostProcessing/Allwmake
+++ b/src/runTimePostProcessing/Allwmake
@@ -6,9 +6,9 @@ cd ${0%/*} || exit 1                            # Run from this directory
 
 echo "======================================================================"
 echo "${PWD##*/} : $PWD"
-echo
 
-unset depend
+unset depend runTimePostProDebug
+
 if [ -d "$VTK_DIR" ]
 then
     depend="VTK_DIR=$VTK_DIR"
@@ -17,25 +17,42 @@ then
     depend="ParaView_DIR=$ParaView_DIR"
 fi
 
-if [ -n "$depend" ]
+# Force use of dummy only
+# unset depend
+
+# For rebuilding (on error) instead of dropping back to dummy
+# runTimePostProDebug=true
+
+if [ "$targetType" = objects ]
 then
-    if [ "$targetType" != objects ]
+    depend=ignore
+elif [ -n "$depend" ]
+then
+    if command -v cmake > /dev/null 2>&1
     then
-        if command -v cmake > /dev/null 2>&1
-        then
-            cmakeVersioned "$depend" $PWD || {
-                echo
-                echo "    WARNING: incomplete build of VTK-based post-processing"
-                echo
-            }
-        else
-            echo "WARNING: skipped - needs cmake"
-        fi
+        cmakeVersioned "$depend" $PWD || {
+            echo
+            echo "    WARNING: incomplete build of VTK-based post-processing"
+            echo
+            if [ -z "$runTimePostProDebug" ]
+            then
+                depend="dummy"
+            fi
+        }
+    else
+        echo "==> skip runTimePostProcessing (needs cmake)"
+        depend="dummy"
     fi
 else
-    echo "WARNING: skipped - needs a VTK or a ParaView installation"
-    echo "    - For ParaView  : export the 'ParaView_DIR' variable"
-    echo "    - For VTK       : export the 'VTK_DIR'      variable"
+    echo "WARNING: skip runTimePostProcessing (no VTK or ParaView)"
+    echo "    - ParaView  : export the 'ParaView_DIR' variable"
+    echo "    - VTK       : export the 'VTK_DIR'      variable"
+fi
+
+if [ "${depend:-dummy}" = dummy ]
+then
+    echo "==> dummy runTimePostProcessing"
+    wmakeVersioned "vtk=dummy" $PWD dummy
 fi
 
 echo "======================================================================"
