GIT: Initial state after latest Foundation merge

diff --git a/src/paraview-plugins/PV3Readers/Allwmake b/src/paraview-plugins/PV3Readers/Allwmake
--- a/src/paraview-plugins/PV3Readers/Allwmake
+++ b/src/paraview-plugins/PV3Readers/Allwmake
@@ -41,19 +41,25 @@ canBuildPlugin()
 
 
 # -----------------------------------------------------------------------------
+
 case "$ParaView_VERSION" in
 3*)
     if canBuildPlugin
     then
-    (
-        # ensure CMake gets the correct C/C++ compilers
-        [ -n "$WM_CC" ]  && export CC="$WM_CC"
+        [ -n "$PV_PLUGIN_PATH" ] || {
+            echo "$0 : PV_PLUGIN_PATH not valid - it is unset"
+            exit 1
+        }
+
+        # Ensure CMake gets the correct C/C++ compilers
+        [ -n "$WM_CC" ] && export CC="$WM_CC"
         [ -n "$WM_CXX" ] && export CXX="$WM_CXX"
 
         wmake $targetType vtkPV3Readers
         PV3blockMeshReader/Allwmake $targetType $*
         PV3FoamReader/Allwmake $targetType $*
-    )
+    else
+        echo "ERROR: ParaView not found in $ParaView_DIR"
     fi
     ;;
 *)
@@ -63,5 +69,6 @@ case "$ParaView_VERSION" in
     echo
     ;;
 esac
+
 
 #------------------------------------------------------------------------------
diff --git a/src/paraview-plugins/PVReaders/Allwmake b/src/paraview-plugins/PVReaders/Allwmake
--- a/src/paraview-plugins/PVReaders/Allwmake
+++ b/src/paraview-plugins/PVReaders/Allwmake
@@ -41,23 +41,29 @@ canBuildPlugin()
 
 
 # -----------------------------------------------------------------------------
+
 case "$ParaView_VERSION" in
 4* | 5*)
     if canBuildPlugin
     then
-    (
+        [ -n "$PV_PLUGIN_PATH" ] || {
+            echo "$0 : PV_PLUGIN_PATH not valid - it is unset"
+            exit 1
+        }
+
         # ensure CMake gets the correct C/C++ compilers
-        [ -n "$WM_CC" ]  && export CC="$WM_CC"
+        [ -n "$WM_CC" ] && export CC="$WM_CC"
         [ -n "$WM_CXX" ] && export CXX="$WM_CXX"
 
         wmake $targetType vtkPVReaders
         PVblockMeshReader/Allwmake $targetType $*
         PVFoamReader/Allwmake $targetType $*
 
-        # dummy directory to trigger proper 'wclean all' behaviour
+        # Dummy directory to trigger proper 'wclean all' behaviour
         # - the Allwclean will otherwise not be used
         mkdir -p Make
-    )
+    else
+        echo "ERROR: ParaView not found in $ParaView_DIR"
     fi
     ;;
 *)
@@ -67,5 +73,6 @@ case "$ParaView_VERSION" in
     echo
     ;;
 esac
+
 
 #------------------------------------------------------------------------------
